apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"name":"demo-app","namespace":"monitoring"},"spec":{"endpoints":[{"bearerTokenFile":"/var/run/secrets/kubernetes.io/serviceaccount/token","interval":"15s","port":"web"}],"namespaceSelector":{"any":true},"selector":{"matchLabels":{"app":"prometheus-demo-app"}}}}
    creationTimestamp: "2019-09-15T08:46:29Z"
    generation: 2
    name: demo-app
    namespace: monitoring
    resourceVersion: "18451"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/demo-app
    uid: 8c81556a-6810-44e3-8ca1-9b307e43f59c
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 15s
      port: web
    namespaceSelector:
      any: true
    selector:
      matchLabels:
        app: prometheus-demo-app
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-apiserver
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-apiserver
    namespace: monitoring
    resourceVersion: "1143"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-apiserver
    uid: 8f7e259f-7167-4ebc-893b-3beccde1e01b
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: https
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: false
        serverName: kubernetes
    jobLabel: component
    namespaceSelector:
      matchNames:
      - default
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-coredns
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-coredns
    namespace: monitoring
    resourceVersion: "1142"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-coredns
    uid: 287b91f9-c408-46d9-8409-6846631ff09a
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: prometheus-operator-coredns
        release: prom-demo
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-grafana
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-grafana
    namespace: monitoring
    resourceVersion: "1151"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-grafana
    uid: 472cbf54-971b-45df-9063-375ffe9db72a
  spec:
    endpoints:
    - path: /metrics
      port: service
    namespaceSelector:
      matchNames:
      - monitoring
    selector:
      matchLabels:
        app: grafana
        release: prom-demo
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-kube-controller-manager
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-kube-controller-manager
    namespace: monitoring
    resourceVersion: "1144"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-kube-controller-manager
    uid: 37d71a00-c741-4717-a6c3-12c711f02a3b
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: prometheus-operator-kube-controller-manager
        release: prom-demo
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-kube-etcd
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-kube-etcd
    namespace: monitoring
    resourceVersion: "1145"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-kube-etcd
    uid: 7d0a8be5-1069-4065-b58f-97d360e45f39
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: prometheus-operator-kube-etcd
        release: prom-demo
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-kube-proxy
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-kube-proxy
    namespace: monitoring
    resourceVersion: "1146"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-kube-proxy
    uid: 795fdb08-d766-46be-8807-2ab9588f6170
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: prometheus-operator-kube-proxy
        release: prom-demo
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-kube-scheduler
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-kube-scheduler
    namespace: monitoring
    resourceVersion: "1147"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-kube-scheduler
    uid: 511efba3-0b0d-48d5-9c41-9d606160aa65
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: prometheus-operator-kube-scheduler
        release: prom-demo
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-kube-state-metrics
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-kube-state-metrics
    namespace: monitoring
    resourceVersion: "1148"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-kube-state-metrics
    uid: 69b2cc72-de20-4d14-90ef-9c3ea3afeedf
  spec:
    endpoints:
    - honorLabels: true
      port: http
    jobLabel: app.kubernetes.io/name
    selector:
      matchLabels:
        app.kubernetes.io/instance: prom-demo
        app.kubernetes.io/name: kube-state-metrics
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-kubelet
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-kubelet
    namespace: monitoring
    resourceVersion: "1149"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-kubelet
    uid: 68b1edf6-a156-4ed2-9588-e39f45cfa0f4
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      port: https-metrics
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      path: /metrics/cadvisor
      port: https-metrics
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    jobLabel: k8s-app
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        k8s-app: kubelet
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-node-exporter
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-node-exporter
    namespace: monitoring
    resourceVersion: "1150"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-node-exporter
    uid: 63c82340-a86b-4884-a4cc-5882d7273ff0
  spec:
    endpoints:
    - port: metrics
    jobLabel: jobLabel
    selector:
      matchLabels:
        app: prometheus-node-exporter
        release: prom-demo
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-operator
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-operator
    namespace: monitoring
    resourceVersion: "1152"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-operator
    uid: 70e1d3ec-cf34-4dba-bb1c-d05fe296f948
  spec:
    endpoints:
    - honorLabels: true
      port: http
    namespaceSelector:
      matchNames:
      - monitoring
    selector:
      matchLabels:
        app: prometheus-operator-operator
        release: prom-demo
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-09-14T17:37:39Z"
    generation: 1
    labels:
      app: prometheus-operator-prometheus
      chart: prometheus-operator-6.7.3
      heritage: Tiller
      release: prom-demo
    name: prom-demo-prometheus-opera-prometheus
    namespace: monitoring
    resourceVersion: "1153"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/prom-demo-prometheus-opera-prometheus
    uid: e2c928b7-4b70-4b74-b34c-7dd5576b0ae8
  spec:
    endpoints:
    - path: /metrics
      port: web
    namespaceSelector:
      matchNames:
      - monitoring
    selector:
      matchLabels:
        app: prometheus-operator-prometheus
        release: prom-demo
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
